export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const START_PRODUCTS_DOWNLOADING = "START_PRODUCTS_DOWNLOADING";
export const DOWNLOAD_PRODUCTS_SUCCESS = "DOWNLOAD_PRODUCTS_SUCCESS";
export const DOWNLOAD_PRODUCTS_ERROR = "DOWNLOAD_PRODUCTS_ERROR";

export const GET_PRODUCT_DELETE = "GET_PRODUCT_DELETE";
export const DELETED_PRODUCT_SUCCESS = "DELETED_PRODUCT_SUCCESS";
export const DELETED_PRODUCT_ERROR = "DELETED_PRODUCT_ERROR";

export const GET_PRODUCT_EDIT = "GET_PRODUCT_EDIT";
export const START_EDIT_PRODUCT = "START_EDIT_PRODUCT";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
